### ISSUE TITLE
bad url for gromos ff bad multiple-time-stepping scheme for a twin-range cut-off

### ISSUE THREAD

**Issue by jruhym** [gromacs/regressiontests#1] opened 2021-06-29 14:57 UTC
In the file https://github.com/gromacs/regressiontests/blob/master/complex/nbnxn-free-energy-vv/reference_d.warn the waring mentions a stale url https://redmine.gromacs.org/issues/2884

**Comment by acmnpv** [comment] 2021-06-29 15:03
Hello, we do all our issue tracking on Gitlab (for this specific project here: https://gitlab.com/gromacs/gromacs-regressiontests/-/issues). I'll close the issue here because of that. Thanks for pointing this out to us!

**Closed as completed by acmnpv** 2021-06-29 15:03 UTC
